config_schema:
  - ["board_0.type", "input"]
  - ["board_1.type", "input"]
  - ["board_2.type", "input"]
  - ["board_3.type", "input"]
  - ["board_4.type", "input"]
  - ["board_5.type", "input"]
  - ["board_6.type", "input"]
  - ["board_7.type", "input"]
  - ["board_8.type", "output"]
  - ["board_9.type", "output"]
  - ["board_10.type", "output"]
  - ["board_11.type", "output"]
  - ["board_12.type", "output"]
  - ["board_13.type", "output"]
  - ["board_14.type", "output"]
  - ["board_15.type", "output"]
